export const PHOTO_ANIMATION_OPTIONS = [
    { id: 'none', label: 'None' },
    // { id: 'slide_left_center', label: 'Left to Center' },
    // { id: 'slide_right_center', label: 'Right to Center' },
    // { id: 'slide_top_center', label: 'Top to Center' },
    // { id: 'slide_bottom_center', label: 'Bottom to Center' },
    // { id: 'slide_top_left', label: 'Top Left Entry' },
    { id: 'slide_top_right', label: 'Top Right Entry' },
    // { id: 'slide_bottom_left', label: 'Bottom Left Entry' },
    // { id: 'slide_bottom_right', label: 'Bottom Right Entry' },
    // { id: 'bounce_left', label: 'Bounce Left' },
    // { id: 'bounce_right', label: 'Bounce Right' },
    // { id: 'bounce_top', label: 'Bounce Top' },
    // { id: 'bounce_bottom', label: 'Bounce Bottom' },
    // { id: 'zoom_in_soft', label: 'Soft Zoom In' },
    // { id: 'zoom_out_soft', label: 'Soft Zoom Out' },
    // { id: 'pulse_soft', label: 'Soft Pulse' },
    // { id: 'pulse_big', label: 'Big Pulse' },
    // { id: 'fade_in', label: 'Fade In' },
    { id: 'fade_up', label: 'Fade Up' },
    // { id: 'fade_down', label: 'Fade Down' },
    { id: 'rotate_soft_left', label: 'Rotate Left' },
    // { id: 'rotate_soft_right', label: 'Rotate Right' },
    // { id: 'flip_x_soft', label: 'Flip X' },
    // { id: 'flip_y_soft', label: 'Flip Y' },
    // { id: 'float_left_right', label: 'Float Left Right' },
    { id: 'float_up_down', label: 'Float Up Down' },
    // { id: 'wiggle_soft', label: 'Soft Wiggle' },
    { id: 'pop_in', label: 'Pop In' },
    // { id: 'drift_top_left', label: 'Drift Top Left' },
    // { id: 'drift_bottom_right', label: 'Drift Bottom Right' },
];

export const getPhotoAnimationLabel = animationId =>
    PHOTO_ANIMATION_OPTIONS.find(option => option.id === animationId)?.label ?? 'None';
